### ISSUE TITLE
Intro text overlaps photo on 1200px-1400px

### ISSUE THREAD

**Issue by KimberlyMunoz** [shannonturner/shannonvturner.com#1]
I noticed this because this is the about the size I keep my window.

Changing #headshot to have a class of `col-lg-3` and #bio to have a class of `col-lg-8` should fix it.

![image](https://cloud.githubusercontent.com/assets/1860176/6723743/8969029e-cda9-11e4-9096-caa1b7ca22ef.png)

**Comment by shannonturner** [comment]
Thank you for reporting this Kim! :cake:
